apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: ack-rds-controller
  name: ack-rds-controller
  annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/ack-rds-controller-d1
